### ISSUE TITLE
Clients needed for operating systems with browsers too old to run Sleepychat with captcha

### ISSUE THREAD

**Issue by Danfun64** [MrMeapify/sleepychat#52]
It is impossible to access Sleepychat from Windows Phone 8.1 because the only web browser it supports is a version of Internet Explorer that is incompatible with the version of Recaptcha used. Considering that there seems to be other problems with sleepychat on the phone, I think a separate client for it and other cases (Wii for example) would be really nice.

**Comment by Elysian-Anon** [comment]
This issue has two problems:

1: The Sleepychat server runs of web-based code (JavaScript). Thus, I am unable to write any clients other than web-based. This means only a browser will ever be able to access Sleepychat. While I try to be accommodating as possible, some browsers just can't possibly run it that well. This is typically the fault of the browser/OS itself. Case and point: problem 2.

2: Sleepychat will ALWAYS use the latest version of Google reCaptcha in order to ensure the best security for every user. It's unfortunate that Win8.1 IE doesn't support it, but I will not compromise security for accessibility.
